export default {
	SAVE_PLAYERS: "SAVE_PLAYERS",
	CHANGE_CURRENT_PLAYER: "CHANGE_CURRENT_PLAYER",
	REDUCE_USER_LIFE: "REDUCE_USER_LIFE",
	RAISE_USER_LIFE: "RAISE_USER_LIFE",
	GAIN_BATTERY: "SAVE_USER_BATTERY",
	SAVE_USER_ENERGY: "SAVE_USER_ENERGY",
};
